server:
  port: 8888
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/nextcare_f
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    ganerate-ddl: true